@baseUrlFilm = http://localhost:3000/films

### Read all films
GET {{baseUrlFilm}}

### Read film by id 
GET {{baseUrlFilm}}/1

### Read film by minimal duration = 140
GET {{baseUrlFilm}}/?minimum-duration=140

### Create a film
POST {{baseUrlFilm}}
Content-Type: application/json

{
    "title":"Kaizen",
    "director":"Inoxtag",
    "duration": 167,
    "budget": 100000
}

### Create a film without title
POST {{baseUrlFilm}}
Content-Type: application/json

{
    "title":,
    "director":"Inoxtag",
    "duration": 167,
    "budget": 100000
}

### Create a film with an invalid duration
POST {{baseUrlFilm}}
Content-Type: application/json

{
    "title":"Kaizen",
    "director":"Inoxtag",
    "duration": -167,
    "budget": 100000
}

### Create a film with an string duration
POST {{baseUrlFilm}}
Content-Type: application/json

{
    "title":"Kaizen",
    "director":"Inoxtag",
    "duration": "167",
    "budget": 100000
}

### Create a film without a mandatory params
POST {{baseUrlFilm}}
Content-Type: application/json

{
    
    "director":"Inoxtag",
    "duration": 167,
    "budget": 100000
}



